<?php
/**
 * ShippingProfilesV1Api
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * OTTO Market API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.69
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace cbdesk\otto\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use cbdesk\otto\Client\ApiException;
use cbdesk\otto\Client\Configuration;
use cbdesk\otto\Client\HeaderSelector;
use cbdesk\otto\Client\ObjectSerializer;

/**
 * ShippingProfilesV1Api Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ShippingProfilesV1Api
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation shippingProfilesV1CreateShippingProfile
     *
     * Create shipping profile
     *
     * @param  \cbdesk\otto\Client\Model\CreateShippingProfileRequestShippingProfilesV1 $body create shipping profile (required)
     * @param  string $authorization Access Token (required)
     *
     * @throws \cbdesk\otto\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \cbdesk\otto\Client\Model\CreateShippingProfileResponseShippingProfilesV1
     */
    public function shippingProfilesV1CreateShippingProfile($body, $authorization)
    {
        list($response) = $this->shippingProfilesV1CreateShippingProfileWithHttpInfo($body, $authorization);
        return $response;
    }

    /**
     * Operation shippingProfilesV1CreateShippingProfileWithHttpInfo
     *
     * Create shipping profile
     *
     * @param  \cbdesk\otto\Client\Model\CreateShippingProfileRequestShippingProfilesV1 $body create shipping profile (required)
     * @param  string $authorization Access Token (required)
     *
     * @throws \cbdesk\otto\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \cbdesk\otto\Client\Model\CreateShippingProfileResponseShippingProfilesV1, HTTP status code, HTTP response headers (array of strings)
     */
    public function shippingProfilesV1CreateShippingProfileWithHttpInfo($body, $authorization)
    {
        $returnType = '\cbdesk\otto\Client\Model\CreateShippingProfileResponseShippingProfilesV1';
        $request = $this->shippingProfilesV1CreateShippingProfileRequest($body, $authorization);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\cbdesk\otto\Client\Model\CreateShippingProfileResponseShippingProfilesV1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\cbdesk\otto\Client\Model\APIErrorResponseForBadRequestShippingProfilesV1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 409:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\cbdesk\otto\Client\Model\APIErrorResponseForConflictShippingProfilesV1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\cbdesk\otto\Client\Model\APIInternalServerErrorResponseShippingProfilesV1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation shippingProfilesV1CreateShippingProfileAsync
     *
     * Create shipping profile
     *
     * @param  \cbdesk\otto\Client\Model\CreateShippingProfileRequestShippingProfilesV1 $body create shipping profile (required)
     * @param  string $authorization Access Token (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function shippingProfilesV1CreateShippingProfileAsync($body, $authorization)
    {
        return $this->shippingProfilesV1CreateShippingProfileAsyncWithHttpInfo($body, $authorization)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation shippingProfilesV1CreateShippingProfileAsyncWithHttpInfo
     *
     * Create shipping profile
     *
     * @param  \cbdesk\otto\Client\Model\CreateShippingProfileRequestShippingProfilesV1 $body create shipping profile (required)
     * @param  string $authorization Access Token (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function shippingProfilesV1CreateShippingProfileAsyncWithHttpInfo($body, $authorization)
    {
        $returnType = '\cbdesk\otto\Client\Model\CreateShippingProfileResponseShippingProfilesV1';
        $request = $this->shippingProfilesV1CreateShippingProfileRequest($body, $authorization);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'shippingProfilesV1CreateShippingProfile'
     *
     * @param  \cbdesk\otto\Client\Model\CreateShippingProfileRequestShippingProfilesV1 $body create shipping profile (required)
     * @param  string $authorization Access Token (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function shippingProfilesV1CreateShippingProfileRequest($body, $authorization)
    {
        // verify the required parameter 'body' is set
        if ($body === null || (is_array($body) && count($body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $body when calling shippingProfilesV1CreateShippingProfile'
            );
        }
        // verify the required parameter 'authorization' is set
        if ($authorization === null || (is_array($authorization) && count($authorization) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $authorization when calling shippingProfilesV1CreateShippingProfile'
            );
        }

        $resourcePath = '/v1/shipping-profiles';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // header params
        if ($authorization !== null) {
            $headerParams['Authorization'] = ObjectSerializer::toHeaderValue($authorization);
        }


        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json;charset=UTF-8']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

            // // this endpoint requires Bearer token
            if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
            }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation shippingProfilesV1DeleteShippingProfile
     *
     * Delete shipping profile
     *
     * @param  string $authorization Access Token (required)
     * @param  string $shipping_profile_id The id of the shipping profile in uuid4 format and the primaryKey for mapping a Profile to a SKU (required)
     *
     * @throws \cbdesk\otto\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function shippingProfilesV1DeleteShippingProfile($authorization, $shipping_profile_id)
    {
        $this->shippingProfilesV1DeleteShippingProfileWithHttpInfo($authorization, $shipping_profile_id);
    }

    /**
     * Operation shippingProfilesV1DeleteShippingProfileWithHttpInfo
     *
     * Delete shipping profile
     *
     * @param  string $authorization Access Token (required)
     * @param  string $shipping_profile_id The id of the shipping profile in uuid4 format and the primaryKey for mapping a Profile to a SKU (required)
     *
     * @throws \cbdesk\otto\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function shippingProfilesV1DeleteShippingProfileWithHttpInfo($authorization, $shipping_profile_id)
    {
        $returnType = '';
        $request = $this->shippingProfilesV1DeleteShippingProfileRequest($authorization, $shipping_profile_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\cbdesk\otto\Client\Model\APIErrorResponseForNotFoundShippingProfilesV1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 412:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\cbdesk\otto\Client\Model\APIErrorResponseForPreconditionShippingProfilesV1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\cbdesk\otto\Client\Model\APIInternalServerErrorResponseShippingProfilesV1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation shippingProfilesV1DeleteShippingProfileAsync
     *
     * Delete shipping profile
     *
     * @param  string $authorization Access Token (required)
     * @param  string $shipping_profile_id The id of the shipping profile in uuid4 format and the primaryKey for mapping a Profile to a SKU (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function shippingProfilesV1DeleteShippingProfileAsync($authorization, $shipping_profile_id)
    {
        return $this->shippingProfilesV1DeleteShippingProfileAsyncWithHttpInfo($authorization, $shipping_profile_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation shippingProfilesV1DeleteShippingProfileAsyncWithHttpInfo
     *
     * Delete shipping profile
     *
     * @param  string $authorization Access Token (required)
     * @param  string $shipping_profile_id The id of the shipping profile in uuid4 format and the primaryKey for mapping a Profile to a SKU (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function shippingProfilesV1DeleteShippingProfileAsyncWithHttpInfo($authorization, $shipping_profile_id)
    {
        $returnType = '';
        $request = $this->shippingProfilesV1DeleteShippingProfileRequest($authorization, $shipping_profile_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'shippingProfilesV1DeleteShippingProfile'
     *
     * @param  string $authorization Access Token (required)
     * @param  string $shipping_profile_id The id of the shipping profile in uuid4 format and the primaryKey for mapping a Profile to a SKU (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function shippingProfilesV1DeleteShippingProfileRequest($authorization, $shipping_profile_id)
    {
        // verify the required parameter 'authorization' is set
        if ($authorization === null || (is_array($authorization) && count($authorization) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $authorization when calling shippingProfilesV1DeleteShippingProfile'
            );
        }
        // verify the required parameter 'shipping_profile_id' is set
        if ($shipping_profile_id === null || (is_array($shipping_profile_id) && count($shipping_profile_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $shipping_profile_id when calling shippingProfilesV1DeleteShippingProfile'
            );
        }

        $resourcePath = '/v1/shipping-profiles/{shippingProfileId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // header params
        if ($authorization !== null) {
            $headerParams['Authorization'] = ObjectSerializer::toHeaderValue($authorization);
        }

        // path params
        if ($shipping_profile_id !== null) {
            $resourcePath = str_replace(
                '{' . 'shippingProfileId' . '}',
                ObjectSerializer::toPathValue($shipping_profile_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

            // // this endpoint requires Bearer token
            if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
            }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'DELETE',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation shippingProfilesV1GetShippingProfileById
     *
     * Get shipping profile by shipping profile id
     *
     * @param  string $authorization Access Token (required)
     * @param  string $shipping_profile_id The id of the shipping profile in uuid4 format and the primaryKey for mapping a Profile to a SKU (required)
     *
     * @throws \cbdesk\otto\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \cbdesk\otto\Client\Model\GetShippingProfileResponseShippingProfilesV1
     */
    public function shippingProfilesV1GetShippingProfileById($authorization, $shipping_profile_id)
    {
        list($response) = $this->shippingProfilesV1GetShippingProfileByIdWithHttpInfo($authorization, $shipping_profile_id);
        return $response;
    }

    /**
     * Operation shippingProfilesV1GetShippingProfileByIdWithHttpInfo
     *
     * Get shipping profile by shipping profile id
     *
     * @param  string $authorization Access Token (required)
     * @param  string $shipping_profile_id The id of the shipping profile in uuid4 format and the primaryKey for mapping a Profile to a SKU (required)
     *
     * @throws \cbdesk\otto\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \cbdesk\otto\Client\Model\GetShippingProfileResponseShippingProfilesV1, HTTP status code, HTTP response headers (array of strings)
     */
    public function shippingProfilesV1GetShippingProfileByIdWithHttpInfo($authorization, $shipping_profile_id)
    {
        $returnType = '\cbdesk\otto\Client\Model\GetShippingProfileResponseShippingProfilesV1';
        $request = $this->shippingProfilesV1GetShippingProfileByIdRequest($authorization, $shipping_profile_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\cbdesk\otto\Client\Model\GetShippingProfileResponseShippingProfilesV1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\cbdesk\otto\Client\Model\APIErrorResponseForNotFoundShippingProfilesV1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\cbdesk\otto\Client\Model\APIInternalServerErrorResponseShippingProfilesV1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation shippingProfilesV1GetShippingProfileByIdAsync
     *
     * Get shipping profile by shipping profile id
     *
     * @param  string $authorization Access Token (required)
     * @param  string $shipping_profile_id The id of the shipping profile in uuid4 format and the primaryKey for mapping a Profile to a SKU (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function shippingProfilesV1GetShippingProfileByIdAsync($authorization, $shipping_profile_id)
    {
        return $this->shippingProfilesV1GetShippingProfileByIdAsyncWithHttpInfo($authorization, $shipping_profile_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation shippingProfilesV1GetShippingProfileByIdAsyncWithHttpInfo
     *
     * Get shipping profile by shipping profile id
     *
     * @param  string $authorization Access Token (required)
     * @param  string $shipping_profile_id The id of the shipping profile in uuid4 format and the primaryKey for mapping a Profile to a SKU (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function shippingProfilesV1GetShippingProfileByIdAsyncWithHttpInfo($authorization, $shipping_profile_id)
    {
        $returnType = '\cbdesk\otto\Client\Model\GetShippingProfileResponseShippingProfilesV1';
        $request = $this->shippingProfilesV1GetShippingProfileByIdRequest($authorization, $shipping_profile_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'shippingProfilesV1GetShippingProfileById'
     *
     * @param  string $authorization Access Token (required)
     * @param  string $shipping_profile_id The id of the shipping profile in uuid4 format and the primaryKey for mapping a Profile to a SKU (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function shippingProfilesV1GetShippingProfileByIdRequest($authorization, $shipping_profile_id)
    {
        // verify the required parameter 'authorization' is set
        if ($authorization === null || (is_array($authorization) && count($authorization) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $authorization when calling shippingProfilesV1GetShippingProfileById'
            );
        }
        // verify the required parameter 'shipping_profile_id' is set
        if ($shipping_profile_id === null || (is_array($shipping_profile_id) && count($shipping_profile_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $shipping_profile_id when calling shippingProfilesV1GetShippingProfileById'
            );
        }

        $resourcePath = '/v1/shipping-profiles/{shippingProfileId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // header params
        if ($authorization !== null) {
            $headerParams['Authorization'] = ObjectSerializer::toHeaderValue($authorization);
        }

        // path params
        if ($shipping_profile_id !== null) {
            $resourcePath = str_replace(
                '{' . 'shippingProfileId' . '}',
                ObjectSerializer::toPathValue($shipping_profile_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json;charset=UTF-8', 'application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json;charset=UTF-8', 'application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

            // // this endpoint requires Bearer token
            if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
            }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation shippingProfilesV1GetShippingProfiles
     *
     * Get all shipping profiles from a partner
     *
     * @param  string $authorization Access Token (required)
     * @param  string $cursor Page number to fetch. This parameter is required to fetch data for specific page number (optional)
     *
     * @throws \cbdesk\otto\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \cbdesk\otto\Client\Model\GetAllShippingProfilesResponseShippingProfilesV1
     */
    public function shippingProfilesV1GetShippingProfiles($authorization, $cursor = null)
    {
        list($response) = $this->shippingProfilesV1GetShippingProfilesWithHttpInfo($authorization, $cursor);
        return $response;
    }

    /**
     * Operation shippingProfilesV1GetShippingProfilesWithHttpInfo
     *
     * Get all shipping profiles from a partner
     *
     * @param  string $authorization Access Token (required)
     * @param  string $cursor Page number to fetch. This parameter is required to fetch data for specific page number (optional)
     *
     * @throws \cbdesk\otto\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \cbdesk\otto\Client\Model\GetAllShippingProfilesResponseShippingProfilesV1, HTTP status code, HTTP response headers (array of strings)
     */
    public function shippingProfilesV1GetShippingProfilesWithHttpInfo($authorization, $cursor = null)
    {
        $returnType = '\cbdesk\otto\Client\Model\GetAllShippingProfilesResponseShippingProfilesV1';
        $request = $this->shippingProfilesV1GetShippingProfilesRequest($authorization, $cursor);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\cbdesk\otto\Client\Model\GetAllShippingProfilesResponseShippingProfilesV1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\cbdesk\otto\Client\Model\APIInternalServerErrorResponseShippingProfilesV1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation shippingProfilesV1GetShippingProfilesAsync
     *
     * Get all shipping profiles from a partner
     *
     * @param  string $authorization Access Token (required)
     * @param  string $cursor Page number to fetch. This parameter is required to fetch data for specific page number (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function shippingProfilesV1GetShippingProfilesAsync($authorization, $cursor = null)
    {
        return $this->shippingProfilesV1GetShippingProfilesAsyncWithHttpInfo($authorization, $cursor)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation shippingProfilesV1GetShippingProfilesAsyncWithHttpInfo
     *
     * Get all shipping profiles from a partner
     *
     * @param  string $authorization Access Token (required)
     * @param  string $cursor Page number to fetch. This parameter is required to fetch data for specific page number (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function shippingProfilesV1GetShippingProfilesAsyncWithHttpInfo($authorization, $cursor = null)
    {
        $returnType = '\cbdesk\otto\Client\Model\GetAllShippingProfilesResponseShippingProfilesV1';
        $request = $this->shippingProfilesV1GetShippingProfilesRequest($authorization, $cursor);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'shippingProfilesV1GetShippingProfiles'
     *
     * @param  string $authorization Access Token (required)
     * @param  string $cursor Page number to fetch. This parameter is required to fetch data for specific page number (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function shippingProfilesV1GetShippingProfilesRequest($authorization, $cursor = null)
    {
        // verify the required parameter 'authorization' is set
        if ($authorization === null || (is_array($authorization) && count($authorization) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $authorization when calling shippingProfilesV1GetShippingProfiles'
            );
        }

        $resourcePath = '/v1/shipping-profiles';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($cursor !== null) {
            $queryParams['cursor'] = ObjectSerializer::toQueryValue($cursor, null);
        }
        // header params
        if ($authorization !== null) {
            $headerParams['Authorization'] = ObjectSerializer::toHeaderValue($authorization);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json;charset=UTF-8', 'application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json;charset=UTF-8', 'application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

            // // this endpoint requires Bearer token
            if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
            }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation shippingProfilesV1UpdateShippingProfile
     *
     * Update shipping profile
     *
     * @param  \cbdesk\otto\Client\Model\CreateShippingProfileRequestShippingProfilesV1 $body shipping profile request (required)
     * @param  string $authorization Access Token (required)
     * @param  string $shipping_profile_id The id of the shipping profile in uuid4 format and the primaryKey for mapping a Profile to a SKU (required)
     *
     * @throws \cbdesk\otto\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function shippingProfilesV1UpdateShippingProfile($body, $authorization, $shipping_profile_id)
    {
        $this->shippingProfilesV1UpdateShippingProfileWithHttpInfo($body, $authorization, $shipping_profile_id);
    }

    /**
     * Operation shippingProfilesV1UpdateShippingProfileWithHttpInfo
     *
     * Update shipping profile
     *
     * @param  \cbdesk\otto\Client\Model\CreateShippingProfileRequestShippingProfilesV1 $body shipping profile request (required)
     * @param  string $authorization Access Token (required)
     * @param  string $shipping_profile_id The id of the shipping profile in uuid4 format and the primaryKey for mapping a Profile to a SKU (required)
     *
     * @throws \cbdesk\otto\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function shippingProfilesV1UpdateShippingProfileWithHttpInfo($body, $authorization, $shipping_profile_id)
    {
        $returnType = '';
        $request = $this->shippingProfilesV1UpdateShippingProfileRequest($body, $authorization, $shipping_profile_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\cbdesk\otto\Client\Model\APIErrorResponseForBadRequestShippingProfilesV1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\cbdesk\otto\Client\Model\APIErrorResponseForNotFoundShippingProfilesV1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\cbdesk\otto\Client\Model\APIInternalServerErrorResponseShippingProfilesV1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation shippingProfilesV1UpdateShippingProfileAsync
     *
     * Update shipping profile
     *
     * @param  \cbdesk\otto\Client\Model\CreateShippingProfileRequestShippingProfilesV1 $body shipping profile request (required)
     * @param  string $authorization Access Token (required)
     * @param  string $shipping_profile_id The id of the shipping profile in uuid4 format and the primaryKey for mapping a Profile to a SKU (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function shippingProfilesV1UpdateShippingProfileAsync($body, $authorization, $shipping_profile_id)
    {
        return $this->shippingProfilesV1UpdateShippingProfileAsyncWithHttpInfo($body, $authorization, $shipping_profile_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation shippingProfilesV1UpdateShippingProfileAsyncWithHttpInfo
     *
     * Update shipping profile
     *
     * @param  \cbdesk\otto\Client\Model\CreateShippingProfileRequestShippingProfilesV1 $body shipping profile request (required)
     * @param  string $authorization Access Token (required)
     * @param  string $shipping_profile_id The id of the shipping profile in uuid4 format and the primaryKey for mapping a Profile to a SKU (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function shippingProfilesV1UpdateShippingProfileAsyncWithHttpInfo($body, $authorization, $shipping_profile_id)
    {
        $returnType = '';
        $request = $this->shippingProfilesV1UpdateShippingProfileRequest($body, $authorization, $shipping_profile_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'shippingProfilesV1UpdateShippingProfile'
     *
     * @param  \cbdesk\otto\Client\Model\CreateShippingProfileRequestShippingProfilesV1 $body shipping profile request (required)
     * @param  string $authorization Access Token (required)
     * @param  string $shipping_profile_id The id of the shipping profile in uuid4 format and the primaryKey for mapping a Profile to a SKU (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function shippingProfilesV1UpdateShippingProfileRequest($body, $authorization, $shipping_profile_id)
    {
        // verify the required parameter 'body' is set
        if ($body === null || (is_array($body) && count($body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $body when calling shippingProfilesV1UpdateShippingProfile'
            );
        }
        // verify the required parameter 'authorization' is set
        if ($authorization === null || (is_array($authorization) && count($authorization) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $authorization when calling shippingProfilesV1UpdateShippingProfile'
            );
        }
        // verify the required parameter 'shipping_profile_id' is set
        if ($shipping_profile_id === null || (is_array($shipping_profile_id) && count($shipping_profile_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $shipping_profile_id when calling shippingProfilesV1UpdateShippingProfile'
            );
        }

        $resourcePath = '/v1/shipping-profiles/{shippingProfileId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // header params
        if ($authorization !== null) {
            $headerParams['Authorization'] = ObjectSerializer::toHeaderValue($authorization);
        }

        // path params
        if ($shipping_profile_id !== null) {
            $resourcePath = str_replace(
                '{' . 'shippingProfileId' . '}',
                ObjectSerializer::toPathValue($shipping_profile_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json;charset=UTF-8']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

            // // this endpoint requires Bearer token
            if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
            }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'PUT',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
