<?php
/**
 * CreateShippingProfileRequestShippingProfilesV1Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * OTTO Market API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.69
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace cbdesk\otto\Client;

use PHPUnit\Framework\TestCase;

/**
 * CreateShippingProfileRequestShippingProfilesV1Test Class Doc Comment
 *
 * @category    Class
 * @description CreateShippingProfileRequestShippingProfilesV1
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CreateShippingProfileRequestShippingProfilesV1Test extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CreateShippingProfileRequestShippingProfilesV1"
     */
    public function testCreateShippingProfileRequestShippingProfilesV1()
    {
    }

    /**
     * Test attribute "shipping_profile_name"
     */
    public function testPropertyShippingProfileName()
    {
    }

    /**
     * Test attribute "working_days"
     */
    public function testPropertyWorkingDays()
    {
    }

    /**
     * Test attribute "order_cutoff"
     */
    public function testPropertyOrderCutoff()
    {
    }

    /**
     * Test attribute "delivery_type"
     */
    public function testPropertyDeliveryType()
    {
    }

    /**
     * Test attribute "default_processing_time"
     */
    public function testPropertyDefaultProcessingTime()
    {
    }

    /**
     * Test attribute "transport_time"
     */
    public function testPropertyTransportTime()
    {
    }
}
