<?php
/**
 * DHLReturnCarrierCodesReturnsWarehouseV2Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * OTTO Market API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.69
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace cbdesk\otto\Client;

use PHPUnit\Framework\TestCase;

/**
 * DHLReturnCarrierCodesReturnsWarehouseV2Test Class Doc Comment
 *
 * @category    Class
 * @description return carrier codes when carrier in path is DHL
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DHLReturnCarrierCodesReturnsWarehouseV2Test extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "DHLReturnCarrierCodesReturnsWarehouseV2"
     */
    public function testDHLReturnCarrierCodesReturnsWarehouseV2()
    {
    }

    /**
     * Test attribute "leit_code"
     */
    public function testPropertyLeitCode()
    {
    }

    /**
     * Test attribute "settlement_number"
     */
    public function testPropertySettlementNumber()
    {
    }

    /**
     * Test attribute "customer_number"
     */
    public function testPropertyCustomerNumber()
    {
    }
}
