<?php
/**
 * LinkedItemDetailsReceiptsV3Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * OTTO Market API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.69
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace cbdesk\otto\Client;

use PHPUnit\Framework\TestCase;

/**
 * LinkedItemDetailsReceiptsV3Test Class Doc Comment
 *
 * @category    Class
 * @description Additional information to an item directly related to the service. &lt;/br&gt;Object exists only if the service was sold together with an item
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LinkedItemDetailsReceiptsV3Test extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "LinkedItemDetailsReceiptsV3"
     */
    public function testLinkedItemDetailsReceiptsV3()
    {
    }

    /**
     * Test attribute "item_receipt_number"
     */
    public function testPropertyItemReceiptNumber()
    {
    }

    /**
     * Test attribute "item_partner_name"
     */
    public function testPropertyItemPartnerName()
    {
    }

    /**
     * Test attribute "sku"
     */
    public function testPropertySku()
    {
    }

    /**
     * Test attribute "article_number"
     */
    public function testPropertyArticleNumber()
    {
    }

    /**
     * Test attribute "product_title"
     */
    public function testPropertyProductTitle()
    {
    }

    /**
     * Test attribute "service_relations"
     */
    public function testPropertyServiceRelations()
    {
    }
}
