<?php
/**
 * ProductDescriptionProductsV5Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * OTTO Market API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.69
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace cbdesk\otto\Client;

use PHPUnit\Framework\TestCase;

/**
 * ProductDescriptionProductsV5Test Class Doc Comment
 *
 * @category    Class
 * @description Extensive description of the product.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ProductDescriptionProductsV5Test extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ProductDescriptionProductsV5"
     */
    public function testProductDescriptionProductsV5()
    {
    }

    /**
     * Test attribute "category"
     */
    public function testPropertyCategory()
    {
    }

    /**
     * Test attribute "brand_id"
     */
    public function testPropertyBrandId()
    {
    }

    /**
     * Test attribute "product_line"
     */
    public function testPropertyProductLine()
    {
    }

    /**
     * Test attribute "production_date"
     */
    public function testPropertyProductionDate()
    {
    }

    /**
     * Test attribute "multi_pack"
     */
    public function testPropertyMultiPack()
    {
    }

    /**
     * Test attribute "bundle"
     */
    public function testPropertyBundle()
    {
    }

    /**
     * Test attribute "fsc_certified"
     */
    public function testPropertyFscCertified()
    {
    }

    /**
     * Test attribute "disposal"
     */
    public function testPropertyDisposal()
    {
    }

    /**
     * Test attribute "product_url"
     */
    public function testPropertyProductUrl()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "bullet_points"
     */
    public function testPropertyBulletPoints()
    {
    }

    /**
     * Test attribute "attributes"
     */
    public function testPropertyAttributes()
    {
    }
}
