<?php
/**
 * ReceiptReceiptsV3Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * OTTO Market API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.69
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace cbdesk\otto\Client;

use PHPUnit\Framework\TestCase;

/**
 * ReceiptReceiptsV3Test Class Doc Comment
 *
 * @category    Class
 * @description Collection of all details of a receipt
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ReceiptReceiptsV3Test extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ReceiptReceiptsV3"
     */
    public function testReceiptReceiptsV3()
    {
    }

    /**
     * Test attribute "receipt_type"
     */
    public function testPropertyReceiptType()
    {
    }

    /**
     * Test attribute "is_real_receipt"
     */
    public function testPropertyIsRealReceipt()
    {
    }

    /**
     * Test attribute "receipt_number"
     */
    public function testPropertyReceiptNumber()
    {
    }

    /**
     * Test attribute "creation_date"
     */
    public function testPropertyCreationDate()
    {
    }

    /**
     * Test attribute "fulfillment_date"
     */
    public function testPropertyFulfillmentDate()
    {
    }

    /**
     * Test attribute "sales_order_id"
     */
    public function testPropertySalesOrderId()
    {
    }

    /**
     * Test attribute "order_number"
     */
    public function testPropertyOrderNumber()
    {
    }

    /**
     * Test attribute "order_date"
     */
    public function testPropertyOrderDate()
    {
    }

    /**
     * Test attribute "shipment_date"
     */
    public function testPropertyShipmentDate()
    {
    }

    /**
     * Test attribute "shipment"
     */
    public function testPropertyShipment()
    {
    }

    /**
     * Test attribute "linked_receipt_number"
     */
    public function testPropertyLinkedReceiptNumber()
    {
    }

    /**
     * Test attribute "linked_creation_date"
     */
    public function testPropertyLinkedCreationDate()
    {
    }

    /**
     * Test attribute "payment"
     */
    public function testPropertyPayment()
    {
    }

    /**
     * Test attribute "partner"
     */
    public function testPropertyPartner()
    {
    }

    /**
     * Test attribute "customer"
     */
    public function testPropertyCustomer()
    {
    }

    /**
     * Test attribute "delivery_address"
     */
    public function testPropertyDeliveryAddress()
    {
    }

    /**
     * Test attribute "line_items"
     */
    public function testPropertyLineItems()
    {
    }

    /**
     * Test attribute "totals"
     */
    public function testPropertyTotals()
    {
    }

    /**
     * Test attribute "refund_type"
     */
    public function testPropertyRefundType()
    {
    }

    /**
     * Test attribute "partial_refund_type"
     */
    public function testPropertyPartialRefundType()
    {
    }

    /**
     * Test attribute "amount_due"
     */
    public function testPropertyAmountDue()
    {
    }

    /**
     * Test attribute "totals_gross_amount"
     */
    public function testPropertyTotalsGrossAmount()
    {
    }

    /**
     * Test attribute "totals_reductions"
     */
    public function testPropertyTotalsReductions()
    {
    }
}
