<?php
/**
 * ReturnShipmentReturnShipmentsV1Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * OTTO Market API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.69
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace cbdesk\otto\Client;

use PHPUnit\Framework\TestCase;

/**
 * ReturnShipmentReturnShipmentsV1Test Class Doc Comment
 *
 * @category    Class
 * @description A returnShipment with full details.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ReturnShipmentReturnShipmentsV1Test extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ReturnShipmentReturnShipmentsV1"
     */
    public function testReturnShipmentReturnShipmentsV1()
    {
    }

    /**
     * Test attribute "return_shipment_id"
     */
    public function testPropertyReturnShipmentId()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "tracking_key"
     */
    public function testPropertyTrackingKey()
    {
    }

    /**
     * Test attribute "return_position_items"
     */
    public function testPropertyReturnPositionItems()
    {
    }

    /**
     * Test attribute "states"
     */
    public function testPropertyStates()
    {
    }
}
