<?php
/**
 * OrdersV4ApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * OTTO Market API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.69
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace cbdesk\otto\Client\Api;

use cbdesk\otto\Client\Configuration;
use cbdesk\otto\Client\ApiException;
use cbdesk\otto\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * OrdersV4ApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OrdersV4ApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for ordersV4CancelPartnerOrderPositionItems
     *
     * Cancel specific position items of an order.
     *
     */
    public function testOrdersV4CancelPartnerOrderPositionItems()
    {
    }

    /**
     * Test case for ordersV4CancelPartnerOrders
     *
     * Cancel all position items of an order.
     *
     */
    public function testOrdersV4CancelPartnerOrders()
    {
    }

    /**
     * Test case for ordersV4FindPartnerOrders
     *
     * List of orders filtered by fulfillment state.
     *
     */
    public function testOrdersV4FindPartnerOrders()
    {
    }

    /**
     * Test case for ordersV4GetPartnerOrderByOrderNumber
     *
     * Get an order via order number.
     *
     */
    public function testOrdersV4GetPartnerOrderByOrderNumber()
    {
    }

    /**
     * Test case for ordersV4GetPartnerOrderBySalesOrderId
     *
     * Get an order via sales order id.
     *
     */
    public function testOrdersV4GetPartnerOrderBySalesOrderId()
    {
    }
}
