<?php
/**
 * PriceReductionsV1ApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * OTTO Market API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.69
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace cbdesk\otto\Client\Api;

use cbdesk\otto\Client\Configuration;
use cbdesk\otto\Client\ApiException;
use cbdesk\otto\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PriceReductionsV1ApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PriceReductionsV1ApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for priceReductionsV1ApplyPriceReduction
     *
     * Apply price reduction for a positionItemId.
     *
     */
    public function testPriceReductionsV1ApplyPriceReduction()
    {
    }

    /**
     * Test case for priceReductionsV1GetAllReductionsForPartner
     *
     * Get all priceReductions.
     *
     */
    public function testPriceReductionsV1GetAllReductionsForPartner()
    {
    }
}
